version: "3.8"

services:
  insider_code:
    build:
      context: ../
      dockerfile: docker/php/Dockerfile
      args:
        UID: ${USERID}
        GID: ${USERGID}
    container_name: insider_php
    networks:
      - backend
    volumes:
      - ../:/app

  insider_nginx:
    image: nginx
    container_name: insider_nginx
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - insider_code
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/app

networks:
  backend:
